In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

!ln -s /content/gdrive/My\ Drive/Manchester/Courses/Masters/datasets /content/datasets
!ln -s /content/gdrive/My\ Drive/Manchester/Courses/Masters/models /content/models

In [0]:
!pip install bert-embedding
!pip install -e git+https://github.com/negedng/bert-embedding#egg=bert_embedding

!pip install vaderSentiment
!pip install xmltodict
!pip install gensim
!pip install -U spacy
#!python -m spacy download en_core_web_lg

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('tagsets')

!wget -P /root/input/ -c "https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz"

!git clone https://github.com/negedng/argument_BERT

In [3]:
argumentor.trainer("/content/datasets/brat-project/")

Loading data from directory
Detected files: 270
Loaded data length: 27828
-----DATA IS UNBALANCED CURRENT SIZE: 27828 CLASS RATIO: 0.10234296392123042 ... BALANCING DATA
-----BALANCED DATASET WITH SIZE: 5696
Train-test split:5126 570
X-Y data ready: 5126 570
              precision    recall  f1-score   support

  nonrelated       0.82      0.65      0.73       278
     support       0.64      0.85      0.73       259
      attack       0.33      0.06      0.10        33

   micro avg       0.71      0.71      0.71       570
   macro avg       0.60      0.52      0.52       570
weighted avg       0.71      0.71      0.69       570
 samples avg       0.71      0.71      0.71       570



In [1]:
from argument_BERT import argumentor
arg1s = ['Because this is nice!', 'A so welcomed sentence', 'I hope it will work']
arg2s = ["I hope it will work", "as this is a pretty sentence", "Global warming harms the people"]
pred = argumentor.predictor("/content/models/model_example_sa.h5", arg1s, arg2s)

Using TensorFlow backend.
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

Start loading resources...


W0808 13:45:06.363789 140167797352320 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0808 13:45:06.478443 140167797352320 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Generate prediction...
[[0.6934454  0.30577567 0.00077892]
 [0.4461922  0.5284733  0.02533445]
 [0.5490245  0.41705638 0.03391905]]
